name: mayo_cloud_firestore
description: Packake that exposes simple APIs to perform CRUD operations on Firestore
version: 1.0.7
homepage: https://mayosoftware.es

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^3.1.17
  firebase_core: ^1.10.2
  flutter:
    sdk: flutter  
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: ^2.1.5
  fake_cloud_firestore: ^1.3.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  json_serializable: ^6.1.2
  very_good_analysis: ">=3.0.1 <5.0.0"

flutter: