name: mayo_cloud_firestore
description: Packake that exposes simple APIs to perform CRUD operations on Firestore
version: 0.0.1
homepage: https://mayosoftware.es

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: 3.1.17
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1

flutter: